# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mozilla Venezuela
tagline:             'Sitio de la Comunidad Mozilla de Venezuela'
description:         'Somos un grupo creciente de geek y amantes de las nuevas tecnologias, la idea de tener Mozilla Venezuela, es la de construir un puente con las demas comunidades en los demas paises y llevar un ambiente de buena onda en todos los  ambitos.'
url:                 http://mozillavenezuela.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mozilla Venezuela
  url:               https://twitter.com/mozillave
  email:             info@mozillavenezuela.org

# Custom vars
version:             0.0.1

# Writting
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
